// app/calorie/settings/actions.ts
'use server';

import prisma from '@/lib/prisma';
import { ensureUserSettings } from '@/app/calorie/actions';

export async function saveUserSettings(formData: FormData) {
  const userId = await ensureUserSettings();
  const targetCalories = parseInt(formData.get('targetCalories') as string);
  const weight = parseFloat(formData.get('weight') as string);
  const activityLevel = formData.get('activityLevel') as string;

  try {
    await prisma.userSettings.update({
      where: { id: userId },
      data: {
        targetCalories: targetCalories,
        weight: isNaN(weight) ? null : weight,
        activityLevel: activityLevel || null,
      },
    });
    return { success: true };
  } catch (error) {
      // Check if the error is due to a non-existent record (e.g., if ensureUserSettings failed somehow)
      if ((error as any).code === 'P2025') {
        // Handle case where userSettings might not exist, though ensureUserSettings should prevent this
        console.warn('UserSettings not found for update, attempting to create:', userId);
        try {
          await prisma.userSettings.create({
            data: {
              id: userId, // Use the ID generated by ensureUserSettings
              targetCalories: targetCalories,
              weight: isNaN(weight) ? null : weight,
              activityLevel: activityLevel || null,
            },
          });
          return { success: true };
        } catch (createError) {
          console.error('Failed to create user settings after failed update:', createError);
          return { success: false, error: '設定の保存に失敗しました。(作成失敗)' };
        }
      }
    console.error('Failed to save user settings:', error);
    return { success: false, error: '設定の保存に失敗しました。' };
  }
}

export async function saveCustomFood(formData: FormData) {
  const userId = await ensureUserSettings();
  const foodName = formData.get('foodName') as string;
  const foodCalories = parseInt(formData.get('foodCalories') as string);

  if (!foodName || isNaN(foodCalories)) {
    return { success: false, error: '料理名とカロリーを正しく入力してください。' };
  }

  try {
    await prisma.customFood.create({
      data: {
        name: foodName,
        calories: foodCalories,
        userId: userId,
      },
    });
    return { success: true };
  } catch (error) {
    console.error('Failed to save custom food:', error);
    return { success: false, error: 'カスタム料理の保存に失敗しました。' };
  }
}

export async function deleteCustomFood(foodId: string) {
  const userId = await ensureUserSettings(); // Ensure user exists
  try {
    await prisma.customFood.deleteMany({ // Use deleteMany to include userId in where clause for security
      where: {
        id: foodId,
        userId: userId, // Ensure user can only delete their own custom foods
      },
    },
    );
    return { success: true };
  } catch (error) {
    console.error('Failed to delete custom food:', error);
    return { success: false, error: 'カスタム料理の削除に失敗しました。' };
  }
}