/**
 * メッセージマスタ (Message Master)
 * アプリ内の全ユーザー向け文言をここで一括管理します。
 */
/*
使い方：
import { MESSAGE_MASTER } from '@/components/messageMaster';
<FFMessageBox message={MESSAGE_MASTER.GAME.POKER_WIN} />
*/

export const MESSAGE_MASTER = {
  // 1. システム・共通エラー (Error Handling)
  ERROR: {
    DEFAULT: "何らかの問題が発生しました。時間をおいて再度お試しください。",
    TIMEOUT: "通信に時間がかかりすぎています。接続環境を確認してください。",
    QUOTA_EXCEEDED: "【利用制限】現在リクエストが集中しています。1分ほどお待ちください。",
    PAYLOAD_TOO_LARGE: "画像サイズが大きすぎます。自動圧縮を試みましたが制限を超えました。",
    AUTH_REQUIRED: "この機能を利用するにはログインが必要です。",
    NOT_FOUND: "お探しのページまたはデータが見つかりません。",
    INTERNAL_SERVER_ERROR: "サーバー側でエラーが発生しました。管理者へ連絡してください。",
    IMAGE_SAFETY: "画像の解析が制限されました。別の画像でお試しください。",
    EXECUTION_ERROR_TITLE: "実行エラー",
    INVALID_DATA_URI: "無効なData URI形式です。Base64データが見つかりません。",
    EMPTY_BASE64_DATA: "Base64データが空です。画像データを確認してください。",
    BASE64_EXTRACTION_FAILED: "処理後の画像からBase64データを抽出できませんでした。",
    IMAGE_PROCESSING_ERROR: "画像の処理中にエラーが発生しました。画像が破損しているか、サポートされていない形式です。",
    AUTO_RESIZE_FAILED: "画像サイズが大きすぎます。システムによる自動縮小を試みましたが、対応できませんでした。",
    API_KEY_MISSING: "APIキーが設定されていません。",
  },

  // 2. ゲーム演出系 (RPG / Poker Messages)
  GAME: {
    WELCOME: "ようこそ！ すばらしい ぼうけんが あなたを まっています！ ▼",
    GOLD_SHORTAGE: "🪙 が 足りないようです。 カロリーを 記録して 稼ぎましょう。 ▼",
  },

  POKER: {
    BACKGROUND_ALT: "ポーカー背景",
    TITLE: "ハイ＆ロー ポーカー",
    DESCRIPTION: "手持ちのゴールドを増やして10000Gを目指せ！",
    SELECT_START_GOLD: "開始ゴールドを選択:",
    SELECT_INITIAL_BET: "初回ベット額を選択:",
    GAME_START_BUTTON: "ゲームをはじめよう！",
    RETURN_TO_TOP: "トップにもどる",
    GOLD_DISPLAY_PREFIX: "GOLD: ",
    DECK_COUNT_PREFIX: "山札残り: ",
    DECK_COUNT_SUFFIX: " / 54枚",
    CURRENT_PAYOUT_PREFIX: "現在の配当: ",
    MESSAGE_PREFIX: "➤ ",
    CURRENT_CARD_LABEL: "いま",
    NEXT_CARD_LABEL: "つぎ",
    START_ADVENTURE: "ぼうけんに でる",
    QUIT_GAME: "ゲームを やめる",
    RESURRECTION_SPELL: "復活の呪文を となえる (リセット)",
    HIGH_BUTTON: "HIGH (上)",
    LOW_BUTTON: "LOW (下)",
    DOUBLE_UP_CHALLENGE: "ダブルアップに いどむ",
    COLLECT_GOLD: "ゴールドを かいしゅう",
    CLEAR_MESSAGE: "10000G 達成おめでとう！",
    ACHIEVER_NAME_PLACEHOLDER: "名前 (4文字以内, 大文字英字)",
    REGISTER_RANKING: "ランキングに登録",
    LEGENDARY_HERO_RETURN: "➤ 伝説の勇者として 戻る",
    USED_CARD_HISTORY: "でたカード記録",
    BANKRUPTCY_MESSAGE: "破産しました...",
    RANKING_TITLE: "10000G 達成者ランキング",
    NO_ACHIEVERS: "まだ達成者はいません。",
    SUBMITTING_MESSAGE: "Submitting...",
    SUBMIT_ERROR_NAME_INVALID: "Error: Name must be 1 to 4 uppercase alphabetic characters.",
    SUBMIT_SUCCESS_MESSAGE: "Successfully registered!",
    SUBMIT_ERROR_PREFIX: "Error: ",
    START_MESSAGE: "{bet}G はらって ゲームを はじめよう！",
    DECK_RESET_MESSAGE: "山札が なくなったので あたらしく つくった！",
    GUESS_PROMPT: "スライムは {card} をだした！ 上か？下か？",
    DRAW_MESSAGE: "引き分けだ！ {card} のまま やり直し！",
    WIN_MESSAGE: "当たり！ 配当が {payout}G になった！",
    LOSE_MESSAGE: "ざんねんでした！ 全てを失った… ",
    GOAL_ACHIEVED_MESSAGE: "10000G 到達！ おめでとう！ お前の完全勝利だ！",
    COLLECT_MESSAGE: "{bet}G 獲得！ 次はどうする？",
    NEXT_GUESS_PROMPT: "{card} より 上か？下か？",
    POKER_START: "対戦開始です。 手札を 確認してください。 ▼",
    POKER_WIN: "おめでとうございます！ あなたの 勝利です！ 🪙 を獲得しました！ ▼",
    POKER_LOSE: "ざんねん！ コンピュータの 勝利です。 次は がんばりましょう。 ▼",
  },

  // 3. アプリ固有メッセージ (App Specific)
  WORDBOOK: {
    SAVE_SUCCESS: "単語を マスタに 登録しました。",
    DELETE_CONFIRM: "この単語を 削除しても よろしいですか？",
  },
  CALORIE: {
    ANALYZING: "AIが 写真を 解析しています... 少々お待ちください。",
    SUCCESS: "カロリーの 解析が 完了しました！ 100kcal 削り出せそうです。 ▼",
    NO_FOOD_DESCRIPTION: "食事内容が入力されていません。",
    NO_VOICE_INPUT: "音声入力がありません。",
    CALORIE_SAVE_SUCCESS: "登録しました！",
    REGISTERING_LOADING: "登録中...",
    COPYING_LOADING: "コピー中...",
    COPY_PREVIOUS_DAY_LOGS: "前日の記録を今日にコピー",
    DASHBOARD_TITLE: "カロリー記録アプリ - ダッシュボード",
    TODAYS_CALORIES: "本日のカロリー",
    REGISTERED_CALORIES: "登録済みカロリー:",
    TARGET_CALORIES: "目標カロリー:",
    REMAINING_CALORIES: "残りカロリー:",
    TARGET_CALORIES_NOTE: "※目標カロリー設定は設定画面で行えます。",
    PAST_7_DAYS_AVERAGE: "過去7日間の平均カロリー",
    AVERAGE: "平均:",
    VIEW_DETAILED_LOGS: "詳細なログを見る →",
    TODAYS_REGISTERED_MEALS: "本日登録した食事",
    NO_MEALS_REGISTERED: "まだ登録がありません。",
    REGISTER_MEAL_AND_CALORIES: "食事とカロリーを登録する",
    PHOTO: "写真",
    PHOTO_FOR_TRAINING: "写真 (学習用)",
    TEXT: "テキスト",
    VOICE: "音声",
    QUICK_REGISTER: "クイック登録",
    QUICK_REGISTER_NOTE: "まだ登録がありません。食事を登録するとここに頻繁なメニューが表示されます。",
    COPY_PREVIOUS_DAY_RECORDS: "前日の記録をコピー",
    SETTINGS_TITLE: "カロリー記録アプリ - 設定",
    SETTINGS_TARGET_BODY_INFO: "目標・身体情報設定",
    SETTINGS_TARGET_CALORIES_LABEL: "目標カロリー (kcal)",
    SETTINGS_WEIGHT_LABEL: "体重 (kg)",
    SETTINGS_ACTIVITY_LEVEL_LABEL: "活動レベル",
    SETTINGS_ACTIVITY_LEVEL_PLACEHOLDER: "選択してください",
    SETTINGS_ACTIVITY_LEVEL_SEDENTARY: "座りがち (ほとんど運動しない)",
    SETTINGS_ACTIVITY_LEVEL_LIGHT: "軽度 (週1-3日軽い運動)",
    SETTINGS_ACTIVITY_LEVEL_MODERATE: "中度 (週3-5日中程度の運動)",
    SETTINGS_ACTIVITY_LEVEL_ACTIVE: "高強度 (週6-7日激しい運動)",
    SETTINGS_SAVE_BUTTON: "設定を保存",
    CUSTOM_FOOD_MASTER_TITLE: "カスタム料理マスタ",
    CUSTOM_FOOD_NAME_LABEL: "料理名",
    CUSTOM_FOOD_CALORIES_LABEL: "カロリー (kcal)",
    CUSTOM_FOOD_ADD_BUTTON: "カスタム料理を追加",
    CUSTOM_FOOD_REGISTERED_LIST_TITLE: "登録済みカスタム料理",
    CUSTOM_FOOD_NO_FOODS_REGISTERED: "カスタム料理はまだ登録されていません。",
    DELETE_BUTTON: "削除",
  },
  ROCKET_GAME: {
    LEVEL_NAMES: {
      1: "Lv.1: 理想の放物線",
      2: "Lv.2: 山を越えろ",
      3: "Lv.3: 高台のターゲット",
      4: "Lv.4: 空気抵抗の壁",
      5: "Lv.5: 抵抗と山",
      6: "Lv.6: 抵抗と高台",
      7: "Lv.7: 真夏の方程式（風あり）",
    },
    HINTS: {
      parabolic: "ヒント1: 放物運動の基本を理解しましょう。最高の飛距離は45度で得られます。",
      pressure: "ヒント2: 圧力が高いほど初速が上がります。",
      angle: "ヒント3: 角度は飛距離と高度のバランスを決めます。",
      drag: "ヒント4: 空気抵抗がある場合、最適角度は45度より少し小さくなります。",
      obstacle: "ヒント5: 山がある場合は高く打ち上げる必要があります。",
    },
    TITLE: "真夏の方程式 ROCKET simulator v1.8",
    MENU_BUTTON: "MENU",
    DISTANCE_DISPLAY: "飛距離:",
    NEXT_LEVEL_QUESTION: "次のレベルへ進みますか？",
    NEXT_LEVEL_BUTTON: "次のレベルへ",
    CONTINUE_LEVEL_BUTTON: "このレベルを続ける",
    RETRY_BUTTON: "[ CLICK TO RETRY ]",
    ATTEMPT_HISTORY_TITLE: "試行履歴",
    NO_ATTEMPTS_MESSAGE: "まだ試行がありません。",
    HINT_TITLE: "博士のアドバイス",
    SET_RECOMMENDED_VALUES: "おすすめの値をセットする",
  },
  APP_INFO: {
    TITLE: "簡易経営管理ツール",
    DESCRIPTION: "P/L and Word Book Application",
  },
  FEEDBACK: {
    TITLE: "フィードバック掲示板",
    RETURN_HOME: "トップページへ戻る",
    FORM_TITLE: "投稿フォーム",
    NAME_PLACEHOLDER: "名前（任意）",
    CATEGORY_ALL: "全般",
    CATEGORY_POKER: "ポーカー",
    CATEGORY_WORDBOOK: "単語帳",
    CATEGORY_CALORIE: "カロリー",
    CATEGORY_ACCOUNTING: "会計",
    CONTENT_PLACEHOLDER: "フィードバックをどうぞ（100字以内）",
    SUBMIT_BUTTON: "送信する",
    LIST_TITLE: "フィードバック一覧",
    REPLY_DISPLAY: "返信表示",
    ADMIN_REPLY_TITLE: "管理者からの返信:",
    ADMIN_MENU: "管理者メニュー",
    PASS_PLACEHOLDER: "Pass",
    REPLY_PLACEHOLDER: "返信内容",
    REPLY_BUTTON: "返信",
    DELETE_BUTTON: "削除",
    PASSWORD_INCORRECT: "パスワードが違います",
    ANONYMOUS: "匿名",
  },

  FINANCIAL: {
    PL_DASHBOARD: "損益計算（P/L）ダッシュボード",
    RANDOM_BUTTON: "ランダム",
    REVENUE: "売上高",
    COGS: "売上原価",
    GROSS_PROFIT: "売上総利益",
    SGA: "販売費及び一般管理費",
    OPERATING_INCOME: "営業利益",
    NON_OP_INCOME: "営業外収益",
    NON_OP_EXPENSES: "営業外費用",
    ORDINARY_INCOME: "経常利益",
    SPECIAL_INCOME: "特別利益",
    SPECIAL_LOSSES: "特別損失",
    PRE_TAX_INCOME: "税引前当期純利益",
    TAX: "法人税等",
    NET_INCOME: "当期純利益",
    TAX_RATE_LABEL: "税率",
    DETAIL_PAGE_TITLE_SUFFIX: "の内訳",
    BACK_TO_PL_DASHBOARD: "P/Lダッシュボードに戻る",
    SECTION_NOT_FOUND: "指定されたセクションが見つからないか、内訳編集に対応していません。",
    TOTAL_LABEL: "合計",
    PRESET_BICYCLE: "自転車店",
    PRESET_IT: "IT(ソフト)",
    ITEM_REVENUE_PRODUCT: "製品売上",
    ITEM_REVENUE_SERVICE: "サービス売上",
    ITEM_COGS_PURCHASE: "仕入高",
    ITEM_COGS_MATERIAL: "材料費",
    ITEM_SGA_SALARY: "人件費",
    ITEM_SGA_RENT: "家賃",
    ITEM_SGA_AD: "広告宣伝費",
    ITEM_SGA_OTHER: "その他",
    ITEM_BICYCLE_REVENUE_BIKE: "完成車売上",
    ITEM_BICYCLE_REVENUE_PARTS: "パーツ売上",
    ITEM_BICYCLE_REVENUE_REPAIR: "修理・メンテ",
    ITEM_BICYCLE_COGS_BIKE: "完成車仕入",
    ITEM_BICYCLE_COGS_PARTS: "パーツ仕入",
    ITEM_BICYCLE_SGA_SALARY: "人件費",
    ITEM_BICYCLE_SGA_RENT: "店舗家賃",
    ITEM_BICYCLE_SGA_UTILITIES: "水道光熱費",
    ITEM_BICYCLE_SGA_AD: "広告費",
    ITEM_NON_OP_INCOME_INTEREST: "受取利息",
    ITEM_NON_OP_EXPENSES_INTEREST: "支払利息",
    ITEM_IT_REVENUE_LICENSE: "ライセンス売上",
    ITEM_IT_REVENUE_CONTRACT: "開発受託",
    ITEM_IT_REVENUE_SUPPORT: "保守サポート",
    ITEM_IT_COGS_SERVER: "サーバー費用",
    ITEM_IT_COGS_SOFTWARE: "外部ソフト利用料",
    ITEM_IT_SGA_SALARY: "役員報酬",
    ITEM_IT_SGA_PAYROLL: "給与手当",
    ITEM_IT_SGA_RENT: "オフィス家賃",
    ITEM_IT_SGA_RECRUIT: "採用費",
    ITEM_IT_SGA_AD: "広告宣伝費",
    SECTION_REVENUE: "売上項目",
    SECTION_COGS: "原価項目",
    SECTION_SGA: "販管費項目",
    SECTION_NON_OP_INCOME: "営業外収益項目",
    SECTION_NON_OP_EXPENSES: "営業外費用項目",
    SECTION_SPECIAL_INCOME: "特別利益項目",
    SECTION_SPECIAL_LOSSES: "特別損失項目",
  },

  HOME: {
    APP_FINANCIAL_SIM_NAME: "経営シミュレーションゲーム",
    APP_FINANCIAL_SIM_DESC: "簿記を学ぶための経営シミュレーションゲーム。",
    APP_WORDBOOK_NAME: "Wikipedia風単語帳",
    APP_WORDBOOK_DESC: "あなたの学習メモから単語と定義を登録できるパーソナル単語帳。",
    APP_CALORIE_NAME: "カロリー記録アプリ",
    APP_CALORIE_DESC: "写真を撮るだけでAIがカロリーを推定し、目標達成を視覚的にサポートします。",
    APP_POKER_NAME: "ハイ＆ロー ポーカー",
    APP_POKER_DESC: "コンピュータとポーカーで対戦できます。戦略を練って勝利を目指しましょう！",
    APP_ROCKET_GAME_NAME: "ロケットゲーム",
    APP_ROCKET_GAME_DESC: "ペットボトルロケットの物理演算をシミュレートするゲームアプリです。",
    APP_FEEDBACK_NAME: "フィードバック掲示板",
    APP_FEEDBACK_DESC: "ご意見・ご要望をお寄せください。",
    APP_DEVLOG_NAME: "開発日記",
    APP_DEVLOG_DESC: "日々の開発記録を綴りましょう。",
    BACKGROUND_ALT: "車輪再発明室 背景",
    TABLE_HEADER_APP: "Application",
    TABLE_HEADER_VERSION: "Version",
    OPEN_BUTTON: "Open",
    DESCRIPTION_LABEL: "Description:",
  },
} as const;

/**
 * キーを指定してメッセージを取得する関数
 * 将来的にデータベース（Firestore）から取得するように拡張も可能です。
 */
export function getMessage(category: keyof typeof MESSAGE_MASTER, key: string): string {
  const cat: any = MESSAGE_MASTER[category];
  return cat[key] || MESSAGE_MASTER.ERROR.DEFAULT;
}